"""Unix man page generation for Tooli apps."""

from __future__ import annotations

import datetime
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from tooli.app import Tooli


def generate_man_page(app: Tooli) -> str:
    """Generate a basic Unix man page in roff format."""
    name = (app.info.name or "tooli-app").upper()
    description = app.info.help or "An agent-native CLI application."
    date = datetime.date.today().strftime("%Y-%m-%d")

    lines: list[str] = []
    lines.append(f'.TH {name} 1 "{date}" "Tooli" "User Commands"')
    lines.append(".SH NAME")
    lines.append(rf"{name.lower()} \- {description}")

    lines.append(".SH SYNOPSIS")
    lines.append(rf"\fB{name.lower()}\fR [\fIGLOBAL_OPTIONS\fR] \fBCOMMAND\fR [\fIARGS\fR...]")

    lines.append(".SH DESCRIPTION")
    lines.append(description)
    lines.append("Tooli apps are simultaneously human-friendly and machine-consumable.")

    lines.append(".SH GLOBAL OPTIONS")
    lines.append(".TP")
    lines.append(r"\fB\-\-output\fR \fIMODE\fR")
    lines.append("Output format: auto|json|jsonl|text|plain")
    lines.append(".TP")
    lines.append(r"\fB\-\-quiet\fR, \fB\-q\fR")
    lines.append("Suppress non-essential output.")
    lines.append(".TP")
    lines.append(r"\fB\-\-verbose\fR, \fB\-v\fR")
    lines.append("Increase verbosity.")
    lines.append(".TP")
    lines.append(r"\fB\-\-dry\-run\fR")
    lines.append("Show planned actions without executing.")
    lines.append(".TP")
    lines.append(r"\fB\-\-schema\fR")
    lines.append("Output JSON Schema for the command and exit.")

    lines.append(".SH COMMANDS")
    for tool_def in app.get_tools():
        if tool_def.hidden:
            continue
        lines.append(".TP")
        lines.append(rf"\fB{tool_def.name}\fR")
        lines.append(tool_def.help or tool_def.callback.__doc__ or "")

    lines.append(".SH EXIT CODES")
    lines.append("0: Success")
    lines.append(".IP")
    lines.append("2: Invalid usage / validation error")
    lines.append(".IP")
    lines.append("10: Not found / state error")
    lines.append(".IP")
    lines.append("70: Internal or runtime error")

    lines.append(".SH AUTHOR")
    lines.append("Generated by Tooli.")

    return "\n".join(lines)
