//! Runtime wrapper for a Tooli Rust CLI.
//!
//! The previous shape forced every CLI's `main()` to repeat the same six
//! steps (pre-parse for `--schema`, pre-parse for `--agent-manifest`,
//! `try_parse`, branch on the parsed subcommand, handle the missing-command
//! case, plumb the global options through). With `Dispatch` (typically
//! generated by `#[derive(TooliCli)]`) the `App` itself owns those steps and
//! `main()` becomes a five-line dispatch shell.

use crate::command::Command;
use crate::envelope::{EnvelopeMeta, ErrorEnvelope, SuccessEnvelope};
use crate::intent::{detect as detect_intent, machine_output_requested, Intent};
use crate::output::{caller_id_from_env, no_color_requested, resolve_output_mode};
use crate::{
    command_schema, enforce_capabilities, AgentManifest, CommandSchema, Context, Dispatch,
    GlobalOptions, OutputMode, Suggestion, ToolError,
};
use clap::error::Error as ClapError;
use serde::Serialize;
use serde_json::Value;
use std::io::{self, Write};
use std::process::ExitCode;
use std::time::Instant;

/// Runtime wrapper for a Tooli Rust CLI application.
#[derive(Debug, Clone)]
pub struct App {
    name: String,
    version: String,
    description: Option<String>,
}

impl App {
    pub fn new(name: impl Into<String>) -> Self {
        Self {
            name: name.into(),
            version: "0.0.0".to_string(),
            description: None,
        }
    }

    pub fn version(mut self, version: impl Into<String>) -> Self {
        self.version = version.into();
        self
    }

    pub fn description(mut self, description: impl Into<String>) -> Self {
        self.description = Some(description.into());
        self
    }

    pub fn name_str(&self) -> &str {
        &self.name
    }

    pub fn version_str(&self) -> &str {
        &self.version
    }

    /// If argv requests a special intent (`--schema` or `--agent-manifest`),
    /// emit the matching machine-readable response and return its `ExitCode`.
    /// Otherwise return `None` and let the caller continue with normal
    /// parsing.
    pub fn handle_pre_parse_intents<D: Dispatch>(&self) -> Option<ExitCode> {
        match detect_intent(D::names()) {
            Intent::Schema(name) => D::dispatch_schema(name, self, OutputMode::Json),
            Intent::AgentManifest => Some(self.emit_agent_manifest_for::<D>()),
            Intent::Run => None,
        }
    }

    /// Run the parsed subcommand. Handles `--agent-manifest` requested via
    /// the parsed `GlobalOptions`, and surfaces a structured missing-command
    /// error in machine modes.
    pub fn dispatch<D: Dispatch>(&self, global: &GlobalOptions, command: Option<D>) -> ExitCode {
        if global.agent_manifest || global.help_agent {
            return self.emit_agent_manifest_for::<D>();
        }
        match command {
            Some(cmd) => cmd.dispatch(self, global),
            None => self.emit_missing_command(global),
        }
    }

    /// Run a single typed command directly (escape hatch / single-command
    /// CLIs / tests). Most callers should reach this through `Dispatch`.
    pub fn run_command<C>(
        &self,
        command_name: impl Into<String>,
        command: C,
        options: &GlobalOptions,
    ) -> ExitCode
    where
        C: Command,
    {
        let command_name = command_name.into();
        let output_mode = resolve_output_mode(options);
        let context = Context::builder(self.name.clone(), command_name.clone())
            .output_mode(output_mode)
            .no_color(no_color_requested(options))
            .quiet(options.quiet)
            .verbose(options.verbose)
            .dry_run(options.dry_run)
            .yes(options.yes)
            .caller_id(caller_id_from_env())
            .build();

        if options.schema {
            return self.emit_command_schema::<C>(&command_name, output_mode);
        }

        let command_meta = C::meta();
        if let Err(err) = enforce_capabilities(&command_meta) {
            return self.write_error(&command_name, err, options, 0);
        }

        if command_meta.requires_confirmation && !options.yes && !options.dry_run {
            let err = ToolError::input("command requires confirmation")
                .code("E1002")
                .suggestion(Suggestion::new(
                    "confirm",
                    "Pass --yes to confirm this command, or --dry-run to preview it.",
                ));
            return self.write_error(&command_name, err, options, 0);
        }

        let start = Instant::now();
        match command.run(context) {
            Ok(result) => {
                let meta = self.envelope_meta(&command_name, start.elapsed().as_millis(), options);
                match emit_success::<C>(&result, meta, output_mode) {
                    Ok(()) => ExitCode::SUCCESS,
                    Err(err) => {
                        self.write_error(&command_name, err, options, start.elapsed().as_millis())
                    }
                }
            }
            Err(err) => self.write_error(&command_name, err, options, start.elapsed().as_millis()),
        }
    }

    /// Convert a Clap parse error to Tooli output when machine mode was
    /// requested.
    pub fn exit_for_clap_error(&self, error: ClapError) -> ExitCode {
        if machine_output_requested() {
            let tool_error = ToolError::input(error.to_string()).code("E1001");
            let meta = EnvelopeMeta::new(self.name.clone(), self.version.clone(), 0)
                .caller_id(caller_id_from_env());
            let _ = write_error_envelope(tool_error, meta, OutputMode::Json);
        } else {
            let _ = error.print();
        }

        let code = u8::try_from(error.exit_code()).unwrap_or(2);
        ExitCode::from(code)
    }

    /// Emit the schema for a command without executing it. Useful when Clap
    /// would otherwise reject missing positional arguments before the runtime
    /// sees `--schema`.
    pub fn emit_command_schema<C: Command>(
        &self,
        command_name: &str,
        _output_mode: OutputMode,
    ) -> ExitCode {
        let schema = command_schema::<C>(command_name);
        match serde_json::to_string_pretty(&schema) {
            Ok(payload) => {
                println!("{payload}");
                ExitCode::SUCCESS
            }
            Err(err) => {
                eprintln!("failed to serialize schema: {err}");
                ExitCode::from(70)
            }
        }
    }

    /// Emit a complete machine-readable manifest for agents.
    pub fn emit_agent_manifest(
        &self,
        description: impl Into<String>,
        commands: Vec<CommandSchema>,
    ) -> ExitCode {
        let mut manifest = AgentManifest::new(self.name.clone(), self.version.clone(), commands);
        manifest = manifest.description(description);
        match serde_json::to_string_pretty(&manifest) {
            Ok(payload) => {
                println!("{payload}");
                ExitCode::SUCCESS
            }
            Err(err) => {
                eprintln!("failed to serialize agent manifest: {err}");
                ExitCode::from(70)
            }
        }
    }

    /// Emit a manifest using the schemas from a `Dispatch` impl. The
    /// description comes from the `App::description()` setting.
    pub fn emit_agent_manifest_for<D: Dispatch>(&self) -> ExitCode {
        let description = self.description.clone().unwrap_or_default();
        self.emit_agent_manifest(description, D::schemas())
    }

    /// Emit a structured Tooli error for application-level failures.
    pub fn emit_error(
        &self,
        command_name: &str,
        error: ToolError,
        options: &GlobalOptions,
    ) -> ExitCode {
        self.write_error(command_name, error, options, 0)
    }

    fn emit_missing_command(&self, options: &GlobalOptions) -> ExitCode {
        let mode = resolve_output_mode(options);
        if matches!(mode, OutputMode::Json | OutputMode::Jsonl) {
            return self.emit_error(
                self.name.clone().as_str(),
                ToolError::input("missing command")
                    .code("E1001")
                    .suggestion(Suggestion::new(
                        "discover",
                        format!("Run `{} --agent-manifest` to list commands.", self.name),
                    )),
                options,
            );
        }
        eprintln!(
            "{} requires a subcommand. Run `{} --help` to list commands.",
            self.name, self.name
        );
        ExitCode::from(2)
    }

    fn envelope_meta(
        &self,
        command_name: &str,
        duration_ms: u128,
        options: &GlobalOptions,
    ) -> EnvelopeMeta {
        EnvelopeMeta::new(
            format!("{}.{}", self.name, command_name),
            self.version.clone(),
            duration_ms,
        )
        .dry_run(options.dry_run)
        .caller_id(caller_id_from_env())
    }

    fn write_error(
        &self,
        command_name: &str,
        error: ToolError,
        options: &GlobalOptions,
        duration_ms: u128,
    ) -> ExitCode {
        let mode = resolve_output_mode(options);
        let exit_code = error.exit_code();
        let meta = self.envelope_meta(command_name, duration_ms, options);
        let _ = write_error_envelope(error, meta, mode);
        ExitCode::from(exit_code)
    }
}

fn emit_success<C: Command>(
    result: &C::Output,
    meta: EnvelopeMeta,
    output_mode: OutputMode,
) -> crate::Result<()> {
    match output_mode {
        OutputMode::Json => {
            let envelope = SuccessEnvelope::new(result, meta);
            println!(
                "{}",
                serde_json::to_string_pretty(&envelope).map_err(json_error)?
            );
        }
        OutputMode::Jsonl => emit_jsonl(result, meta)?,
        OutputMode::Auto | OutputMode::Text | OutputMode::Plain => {
            let mut stdout = io::stdout().lock();
            C::render_human(result, &mut stdout).map_err(io_error)?;
        }
    }
    Ok(())
}

fn emit_jsonl<T: Serialize>(result: &T, meta: EnvelopeMeta) -> crate::Result<()> {
    let value = serde_json::to_value(result).map_err(json_error)?;
    match value {
        Value::Array(items) => {
            for item in items {
                let envelope = SuccessEnvelope::new(&item, meta.clone());
                println!("{}", serde_json::to_string(&envelope).map_err(json_error)?);
            }
        }
        value => {
            let envelope = SuccessEnvelope::new(&value, meta);
            println!("{}", serde_json::to_string(&envelope).map_err(json_error)?);
        }
    }
    Ok(())
}

fn write_error_envelope(
    error: ToolError,
    meta: EnvelopeMeta,
    output_mode: OutputMode,
) -> io::Result<()> {
    match output_mode {
        OutputMode::Json | OutputMode::Jsonl => {
            let envelope = ErrorEnvelope::new(error, meta);
            println!("{}", serde_json::to_string_pretty(&envelope)?);
        }
        OutputMode::Auto | OutputMode::Text | OutputMode::Plain => {
            let mut stderr = io::stderr().lock();
            writeln!(stderr, "Error: {}", error.message)?;
            if let Some(suggestion) = error.suggestion_ref() {
                writeln!(stderr, "Suggestion: {}", suggestion.fix)?;
            }
        }
    }
    Ok(())
}

fn json_error(error: serde_json::Error) -> ToolError {
    ToolError::internal(format!("JSON serialization failed: {error}")).code("E5001")
}

fn io_error(error: io::Error) -> ToolError {
    ToolError::internal(format!("output failed: {error}")).code("E5002")
}
